#ifdef OPT_Scheduler

XYBlock1DColoringStructuredMeshSchedule::buildXYBlock1DColoringStructuredMeshSchedule(mesh);

XYBlock1DColoringStructuredMeshSchedule::getXYBlock1DColoringStructuredMeshSchedule().show();

// XBlock2DPartitionStructuredMeshSchedule::buildXBlock2DPartitionStructuredMeshSchedule(mesh);

// XBlock2DPartitionStructuredMeshSchedule::getXBlock2DPartitionStructuredMeshSchedule().show();

#endif



// MPI_Barrier(MPI_COMM_WORLD);
// MPI_Abort(MPI_COMM_WORLD, -1);